const cartActionType = {
    ADD_ITEM_CART: "ADD_ITEM_CART",
    ADD_ITEM_CART_SUCCESS: "ADD_ITEM_CART_SUCCESS",
    DELETE_ITEM_CART:"DELETE_ITEM_CART",
    DELETE_ITEM_CART_SUCCESS:"DELETE_ITEM_CART_SUCCESS",
    DELETE_ALL_CART:"DELETE_ALL_CART"
  };
  
  export default cartActionType;
  