const orderActionType = {
    CREATE_ORDER: "CREATE_ORDER",
    CREATE_ORDER_PROCESSING: "CREATE_ORDER_PROCESSING",
    CREATE_ORDER_SUCCESS:"CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAIL:"CREATE_ORDER_FAIL",

    CREATE_ORDER_DETAIL: "CREATE_ORDER_DETAIL",
    CREATE_ORDER_DETAIL_SUCCESS: "CREATE_ORDER_DETAIL_SUCCESS",
    CREATE_ORDER_DETAIL_FAIL:"CREATE_ORDER_DETAIL_FAIL",

    GET_ORDER_BY_USER:"GET_ORDER_BY_USER",
    GET_ORDER_BY_USER_SUCCESS:"GET_ORDER_BY_USER_SUCCESS",


    STOP_ALL_ACTION:"STOP_ALL_ACTION"



  };
  
  export default orderActionType;
  