const UserActionTypes = {

    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_PROCESSING: 'SIGN_IN_PROCESSING',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_PROCESSING: 'SIGN_UP_PROCESSING',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',

    SIGN_OUT_START:'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',

    SAVE_USER_START: " SAVE_USER_START",
    SAVE_USER_PROCCESING: "SAVE_USER_PROCCESING",
    SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
    SAVE_USER__FAIL: "SAVE_USER__FAIL",

    REFRESH_USER :'REFRESH_USER',
    STOP_ALL_ACTION:"STOP_ALL_ACTION"
  };
  export default UserActionTypes;
  